## Assignment 1

# 1. String Variable

In [1]:
import random

# Create variables
student_name = ['Neha Gopi', 'Likitha DT', 'Mohan Krian', 'Pranav Ramesh', 'Gokul']
course_name = ['Data Science Professional', 'IT Professional', 'IT Professional', 'MBA International', 'Data Science Professional']
email_address = ['neha@gmail.com', 'likitha@gmail.com', 'mohan@gmail.com', 'pranav@gmail.com', 'gokul@gmail.com']

# Add  values to each variable
for _ in range(5):
    student_name.append("Student" + str(random.randint(1, 100)))
    course_name.append("Course" + str(random.randint(1, 100)))
    email_address.append("email" + str(random.randint(1, 100)) + "@example.com")

# Print the values
print("Student Names:", student_name)
print("Course Names:", course_name)
print("Email Addresses:", email_address)


Student Names: ['Neha Gopi', 'Likitha DT', 'Mohan Krian', 'Pranav Ramesh', 'Gokul', 'Student97', 'Student78', 'Student41', 'Student44', 'Student45']
Course Names: ['Data Science Professional', 'IT Professional', 'IT Professional', 'MBA International', 'Data Science Professional', 'Course54', 'Course22', 'Course92', 'Course80', 'Course56']
Email Addresses: ['neha@gmail.com', 'likitha@gmail.com', 'mohan@gmail.com', 'pranav@gmail.com', 'gokul@gmail.com', 'email17@example.com', 'email85@example.com', 'email93@example.com', 'email9@example.com', 'email55@example.com']


# 2. Three Variables

In [2]:
# Define the string variable with the name
my_name = "Srivatsa Gaurav Addala"

# Print characters at odd positions
print("Characters at odd positions:")
for i in range(0, len(my_name), 2):
    print(my_name[i], end=' ')

# Print characters at even positions
print("\nCharacters at even positions:")
for i in range(1, len(my_name), 2):
    print(my_name[i], end=' ')


Characters at odd positions:
S i a s   a r v A d l 
Characters at even positions:
r v t a G u a   d a a 

# 3. Create Dict

In [3]:
# Create a dictionary variable
student_info = {}

# Insert values into the dictionary
student_info['Student name'] = student_name
student_info['Course name'] = course_name
student_info['EmailAddress'] = email_address

# Print the dictionary
print("Student Information:")
print(student_info)


Student Information:
{'Student name': ['Neha Gopi', 'Likitha DT', 'Mohan Krian', 'Pranav Ramesh', 'Gokul', 'Student97', 'Student78', 'Student41', 'Student44', 'Student45'], 'Course name': ['Data Science Professional', 'IT Professional', 'IT Professional', 'MBA International', 'Data Science Professional', 'Course54', 'Course22', 'Course92', 'Course80', 'Course56'], 'EmailAddress': ['neha@gmail.com', 'likitha@gmail.com', 'mohan@gmail.com', 'pranav@gmail.com', 'gokul@gmail.com', 'email17@example.com', 'email85@example.com', 'email93@example.com', 'email9@example.com', 'email55@example.com']}


# 4. Define String Variable

In [4]:
# Define the energy variable
energy = 'Fossil'  

if energy == 'Fossil':
    print("Natural gas")
else:
    print("Solar power")


Natural gas


# 5 . Print Prime Numbers

In [5]:
# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Print prime numbers between 0 and 100
print("Prime numbers between 0 and 100:")
for number in range(101):
    if is_prime(number):
        print(number)


Prime numbers between 0 and 100:
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


# 6. Break a Loop

Yes, it is possible to break a loop before executing for the defined number of iterations using a while loop in Python. The break statement is used to exit a loop prematurely. Here's an example:



In this example, the while loop continues as long as counter is less than 10. However, there is a condition (counter == limit) inside the loop that triggers the break statement, causing the loop to terminate prematurely when the condition is met. This allows you to break out of the loop before reaching the defined number of iterations.

If you want to break a for loop before the defined number of iterations, a similar approach can be used with the break statement. However, for loops in Python are generally designed to iterate over a sequence, so the control flow is typically less flexible than with a while loop.

In [6]:
counter = 0
limit = 5

while counter < 10:
    print("Current counter value:", counter)
    
    if counter == limit:
        print("Breaking the loop before the defined number of iterations.")
        break
    
    counter += 1


Current counter value: 0
Current counter value: 1
Current counter value: 2
Current counter value: 3
Current counter value: 4
Current counter value: 5
Breaking the loop before the defined number of iterations.


# 7. Functions 

In [7]:
# Function  addition
def Addition(x, y):
    return x + y

# Function  multiplication
def Multiplication(x, y):
    return x * y

# Function  division
def Division(x, y):
    if y != 0:
        return x / y
    else:
        return "Cannot divide by zero"

# Function subtraction
def Subtraction(x, y):
    return x - y

# Call the functions 
result_addition = Addition(4, 7)
result_multiplication = Multiplication(4, 7)
result_division = Division(4, 7)
result_subtraction = Subtraction(4, 7)

# Print the outputs
print("Addition:", result_addition)
print("Multiplication:", result_multiplication)
print("Division:", result_division)
print("Subtraction:", result_subtraction)


Addition: 11
Multiplication: 28
Division: 0.5714285714285714
Subtraction: -3


# 8. Create Matrix

In [8]:
import numpy as np

# Create an 8x8 identity matrix
identity_matrix = np.identity(8)
print("8x8 Identity Matrix:")
print(identity_matrix)
print()

# Create an 8x4 random matrix
random_matrix = np.random.random((8, 4))
print("8x4 Random Matrix:")
print(random_matrix)
print()

# Multiply the identity matrix with the random matrix
result_matrix = np.dot(identity_matrix, random_matrix)
print("Result Matrix after multiplying Identity matrix with Random matrix:")
print(result_matrix)


8x8 Identity Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

8x4 Random Matrix:
[[0.95534373 0.93437188 0.66791906 0.76932291]
 [0.03592968 0.63792042 0.40116111 0.90063842]
 [0.04440888 0.22491857 0.7732528  0.91385075]
 [0.63803878 0.46855974 0.85365418 0.91052168]
 [0.41255532 0.80118762 0.46885145 0.77081298]
 [0.49398766 0.85894834 0.5238975  0.88456152]
 [0.61235481 0.08885146 0.97703874 0.41794709]
 [0.30390918 0.77320829 0.97095882 0.62681447]]

Result Matrix after multiplying Identity matrix with Random matrix:
[[0.95534373 0.93437188 0.66791906 0.76932291]
 [0.03592968 0.63792042 0.40116111 0.90063842]
 [0.04440888 0.22491857 0.7732528  0.91385075]
 [0.63803878 0.46855974 0.85365418 0.91052168]
 [0.41255532 0.80118762 0.46885145 0.77081298]
 [0.49398766 0.85894834 0.5238975  0.88456152]
 [0.61235481 0

# 9. Create a 8X9 Matrix

In [9]:
# Create an 8x9 matrix with random values
original_matrix = np.random.random((8, 9))
print("Original 8x9 Matrix:")
print(original_matrix)
print()

# Transpose the matrix
transposed_matrix = np.transpose(original_matrix)
print("Transposed 9x8 Matrix:")
print(transposed_matrix)

Original 8x9 Matrix:
[[0.85527691 0.51594508 0.8547578  0.87110652 0.86370886 0.9582921
  0.55083419 0.15214443 0.53204085]
 [0.8686851  0.6835292  0.95455566 0.97794023 0.39926108 0.18984645
  0.45452608 0.5890776  0.7633494 ]
 [0.92912642 0.4517594  0.16700938 0.98310805 0.91129135 0.15700584
  0.68263124 0.07948443 0.66903906]
 [0.53393822 0.3223714  0.51169274 0.77047072 0.71805378 0.32662155
  0.85290779 0.75985037 0.20208253]
 [0.1653931  0.77003156 0.54336152 0.07030657 0.88217287 0.32025548
  0.91058279 0.46971654 0.97089195]
 [0.80113581 0.74468565 0.22046751 0.42622609 0.7632196  0.3889261
  0.62536762 0.18808479 0.76056643]
 [0.5416324  0.50141196 0.51843477 0.19691809 0.13319159 0.97152489
  0.90827224 0.52960914 0.03197305]
 [0.41491722 0.88807245 0.91389424 0.039486   0.03584073 0.30686687
  0.56068345 0.37419468 0.07077089]]

Transposed 9x8 Matrix:
[[0.85527691 0.8686851  0.92912642 0.53393822 0.1653931  0.80113581
  0.5416324  0.41491722]
 [0.51594508 0.6835292  0.45175

# 10. PEDESTRIAN COUNTING MATRIX

In [10]:
import pandas as pd

file_path = "pedestrian-counting-system-monthly-counts-per-hour.csv"
data = pd.read_csv(file_path)

# Display the shape of the dataset
num_instances, num_variables = data.shape
print(f"Number of data instances: {num_instances}")
print(f"Number of variables/features: {num_variables}")
print()

# Calculate the mean of the third variable
variable_index = 2
variable_name = data.columns[variable_index]
variable_mean = data.iloc[:, variable_index].mean()
print(f"Mean of {variable_name}: {variable_mean}")

modified_values = data.iloc[:, variable_index] - variable_mean

# Print both original and modified values
print("\nOriginal Values:")
print(data.iloc[:, variable_index])

print("\nModified Values (Mean Deducted):")
print(modified_values)


Number of data instances: 525005
Number of variables/features: 7

Mean of LocationID: 53.17730497804783

Original Values:
0          51
1          51
2          51
3          51
4          51
         ... 
525000    142
525001    142
525002    142
525003    142
525004    142
Name: LocationID, Length: 525005, dtype: int64

Modified Values (Mean Deducted):
0         -2.177305
1         -2.177305
2         -2.177305
3         -2.177305
4         -2.177305
            ...    
525000    88.822695
525001    88.822695
525002    88.822695
525003    88.822695
525004    88.822695
Name: LocationID, Length: 525005, dtype: float64
